Data types overview
ZoyaTretyak/js-basic pull request #2
Opened 2019-10-14 14:40 UTC by ZoyaTretyak

2019-10-17 18:24 UTC, lizarusi requested changes

2019-10-17 18:24 UTC, lizarusi commented on Exercises/data-types-overview/data-types-overview.js
> +let numberVariable = 123;
always use `const` when variable not going to be change

2019-10-17 18:24 UTC, lizarusi commented on Exercises/data-types-overview/data-types-overview.js
> +    objOutput[key] += 1;
you can simplify condition

2019-10-17 18:24 UTC, lizarusi commented on Exercises/data-types-overview/data-types-overview.js
> +for (i ; i < piu.length ; i++) {
also try to use https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce here

2019-10-27 18:22 UTC, Mike-Savin approved these changes
👍

2019-10-28 13:20 UTC, merged