strings
ZoyaTretyak/js-basic pull request #3
Opened 2019-10-15 07:36 UTC by ZoyaTretyak

2019-10-30 14:43 UTC, lizarusi requested changes
very nice!

2019-10-30 14:43 UTC, lizarusi commented on Exercises/strings/strings.js
> +const myFavoriteAnimal = 'cat';
mine too!

2019-10-30 14:43 UTC, lizarusi commented on Exercises/strings/strings.js
> +console.log(firstLetter1 + firstName.slice(1) +' '+ firstLetter2 + lastName.slice(1));
try to use back-ticks here

2019-10-30 14:43 UTC, lizarusi commented on Exercises/strings/strings.js
> +
redundant space

2019-10-30 14:43 UTC, lizarusi commented on Exercises/strings/strings.js
> +  if (pwd.length < 8) {
better to put faster checks to top, because regex perform much longer than check on length

2019-10-30 19:33 UTC, ZoyaTretyak commented on Exercises/strings/strings.js
> +const myFavoriteAnimal = 'cat';
😻

2019-11-01 10:22 UTC, Mike-Savin approved these changes

2019-11-01 14:22 UTC, merged