Numbers
ZoyaTretyak/js-basic pull request #4
Opened 2019-10-29 09:46 UTC by ZoyaTretyak

2019-10-30 14:36 UTC, lizarusi requested changes

2019-10-30 14:36 UTC, lizarusi commented on Exercises/numbers/numbers.js
> +  if (isNaN(number) === true) {
no need to do `===` here. `if` does comparison to `true` behind the scenes

2019-10-30 14:36 UTC, lizarusi commented on Exercises/numbers/numbers.js
> +function randomGenerator(min, max) {
👍

2019-10-30 14:36 UTC, lizarusi commented on Exercises/numbers/numbers.js
> +  return console.log(number);
if you will do `return console.log()` it will return undefined, as `console.log` is function which returns `undefined` so just return number, or text

2019-11-01 09:24 UTC, Mike-Savin approved these changes

2019-11-01 14:23 UTC, merged