Arrays
ZoyaTretyak/js-basic pull request #7
Opened 2019-11-06 16:42 UTC by ZoyaTretyak

2019-11-06 21:12 UTC, lizarusi requested changes

2019-11-06 21:12 UTC, lizarusi commented on Exercises/arrays/arrays.js
> +  const arrayNew = Array.from({ length:arraylength }, () => Math.floor(Math.random() * max));
return new generated array

2019-11-06 21:12 UTC, lizarusi commented on Exercises/arrays/arrays.js
> +  const copyArray = originArray.slice();
return new value. Also consider simplier way

2019-11-06 21:12 UTC, lizarusi commented on Exercises/arrays/arrays.js
> +  const indexElement = array.indexOf(element);
return the index from function

2019-11-06 21:12 UTC, lizarusi commented on Exercises/arrays/arrays.js
> +  const newArray = array1.concat(array2);
consider other way to do it :) and again, return new value from array

2019-11-06 21:12 UTC, lizarusi commented on Exercises/arrays/arrays.js
> +  const copyArray2 = array2;
it will not be pure, array2 will change

2019-11-14 14:01 UTC, Mike-Savin approved these changes
Looks good

2019-11-19 08:36 UTC, merged